[package]
name = "gulf-stream-lib"
version = "0.1.0"
edition = "2021"



[dependencies]
serde = {version = "1.0.156", features = ["derive"] }
bincode = "1.3.3"
sha2 = "0.10.6"
hex-literal = "0.3.4"
tonic = "0.8.3"
prost = "0.11"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
ed25519-dalek = "1"

[build-dependencies]
tonic-build = "0.8"